# Site settings
title: thy blog
email: thy@mail.ecust.edu.cn
description: >-
  thy blog: languages, programming, computer science, math, thoughts
baseurl: "/blog"
url: "http://blog.tianh.tech/"
github_username:  thyecust
mathjax_src: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Build settings
theme: minimal-mistakes-jekyll # dev
remote_theme: mmistakes/minimal-mistakes # deploy
plugins:
  - jekyll-feed
  - jekyll-include-cache
